### ISSUE TITLE
RGB value above 255

### ISSUE THREAD

**Issue by mua1105** [mochman/node-red-contrib-light-transition#10]
Hi!

I'm using v1.4.2 and i'm still getting values above 255 when using the "Half & Half" mode. (pictuere in attachement)

![grafik](https://user-images.githubusercontent.com/99423688/153462944-bb83f1ac-1516-4151-b95d-90ccdcf25890.png)

Thanks for your help, 

Mua

**Comment by mochman** [comment]
Can you tell me what the RGB values of the 3 colors are so I can try and recreate it?  Thanks.

**Comment by mochman** [comment]
This issue should be resolved in 1.4.3.  Please let me know if you run into this issue again.  Thank you.
