### ISSUE TITLE
Second and Seconds settings problem

### ISSUE THREAD

**Issue by pfurrie** [mochman/node-red-contrib-light-transition#13]
I've got the light transition node working with manual settings (settings hard-coded into the node).  However, when I sent a "msg:transition" object to the node, the "units" value isn't being used as it should.  It is provided "Second" but it still maintains the "Minutes" that is hard-coded in my settings in the node... it isn't overridden.  If I try sending "Seconds" instead of "Second" I get an error message -- apparently the plural version doesn't work.  But within the properties of the node, the unit is listed as "Seconds" (plural).  Hence, the msg:transition object can't seem to override the units value.

Solution: allow the msg:transition object to provide the correct version of the unit.

**Comment by mochman** [comment]
Can you provide me the version of this node you are using?
Can you also provide me with the values you hardcoded, as well as the values you are sending to it that don't work?  Thank you.

**Comment by mochman** [comment]
Nevermind, I think I found the problem.  I pushed a new version (1.4.6) to flows.nodered.org.  Please try that version to see if it's working like it should.

**Comment by mochman** [comment]
And for clarification,
msg.transition.units needs to be either "Second", "Minute", or "Hour" (singular, case sensitive) regardless if the associated value is more than 1.

**Comment by pfurrie** [comment]
Thanks, that works!  Great job!
