### ISSUE TITLE
Problem - RGB value components over 255

### ISSUE THREAD

**Issue by vaclavhorejsi** [mochman/node-red-contrib-light-transition#32]
### Terms

- [ ] This request is not a duplicate of an existing issue.
- [X] I have provided as much information as I can to help resolve this issue.

### Description

Hi,
msg.payload.rgb_color componets return value higher then 255. It was "fixed" in #10, but it is still occures. (I am not sure how to reopen closed issue)

### steps-to-reproduce

Set: 
Steps number: 60
Starting color: 194, 168, 0
Middle color: 255, 200, 100 does not matter
End color: 255, 0, 0
Transition: No Transition Color

### Actual Behavior

Between steps 31 to 32 color component (red) changed value from 254 to 256. In next steps is growing high above 255.

step 31
{"_msgid":"eab6f05cb79027af","payload":{"brightness_pct":100,"brightness":255,"rgb_color":[254,108,0],"color_temp":403},"topic":""}

step 32
{"_msgid":"eab6f05cb79027af","payload":{"brightness_pct":100,"brightness":255,"rgb_color":[256,106,0],"color_temp":410},"topic":""}

step 33
{"_msgid":"eab6f05cb79027af","payload":{"brightness_pct":100,"brightness":255,"rgb_color":[258,104,0],"color_temp":416},"topic":""}

### Version

1.7.0

**Comment by mochman** [comment]
I'll take a look, thanks.

**Comment by mochman** [comment]
I just pushed v1.7.1 that should fix this issue.  Please let me know if it's working for you.

**Comment by vaclavhorejsi** [comment]
Thanks. It looks it is ok now.
