### ISSUE TITLE
Brightness integer

### ISSUE THREAD

**Issue by DanNielsen** [mochman/node-red-contrib-light-transition#5]
When using brightness "integer" and input 255 then it only gets output op to 100. If you 255*2,55=651 it will get output to 255 (but get error from node red because the value is over 255).

When using brightness "integer" the output is still "brightness_pct" is should be "brightness".

**Comment by mochman** [comment]
Thanks for pointing out that the brightness limit in integer mode wasn't checked.  I have fixed those cases.

If you check the readme, it states that `integer` mode is only for input.  Right now, this node only outputs in `brightness_pct`.   Integer mode just allows you to send it an initial start/end brightness value in the 0-255 range.

**Comment by DanNielsen** [comment]
THANKS!! :) That was fast
I can only see 1.3.0 in node red? not the 1.3.1 version?

**Comment by mochman** [comment]
It takes a bit for node-red to update their db.

**Comment by mochman** [comment]
I also just created a new enhancement request for outputting values in `brightness` (1-255) along with the other outputs, so that people can choose whichever one they want.

**Comment by DanNielsen** [comment]
Thats cool! Thanks :)Venlig hilsenDan Nielsen3070707728. nov. 2021 14.14 skrev Luke ***@***.***>:
I also just created a new enhancement request for outputting values in brightness (1-255) along with the other outputs, so that people can choose whichever one they want.
