### ISSUE TITLE
payload.brightness

### ISSUE THREAD

**Issue by DanNielsen** [mochman/node-red-contrib-light-transition#9]
Sine dimmers like shelly uses "payload.brightness" and not "payload.brightness_pct". The node should output both, or a way to change the output payload.

**Comment by mochman** [comment]
It has output both since [v1.4.0](https://github.com/mochman/node-red-contrib-light-transition/releases/tag/v1.4.0).  You even [commented on it](https://github.com/mochman/node-red-contrib-light-transition/issues/5#issuecomment-981156690) on your duplicate issue #5.

**Comment by DanNielsen** [comment]
Sorry. You are right it does work :)
